from pydantic import BaseModel, Field


class AgentExecutionMetadata(BaseModel):
    """
    Metadata describing how the agent processed a request.
    """

    model: str = Field(
        default="local",
        description="LLM or execution backend.",
    )

    execution_time: float = Field(
        default=0.0,
        description="Execution time in seconds.",
    )

    tool_calls: int = Field(
        default=0,
        description="Number of tools used.",
    )

    memory_hits: int = Field(
        default=0,
        description="Number of retrieved memory entries.",
    )

    session_id: str = Field(
        default="",
        description="Conversation session identifier.",
    )


class AgentResult(BaseModel):
    """
    Internal response produced by the agent engine.
    """

    answer: str = Field(
        ...,
        description="Final response generated by the agent.",
    )

    metadata: AgentExecutionMetadata = Field(
        default_factory=AgentExecutionMetadata,
    )